name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake and Ninja (via Chocolatey)
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
        shell: powershell

      - name: Clean SDL3 install folder
        run: Remove-Item -Path "C:/SDL3" -Recurse -Force -ErrorAction Ignore
        shell: powershell

      - name: Download and install SDL3
        run: |
          Invoke-WebRequest -Uri https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-3.2.10.tar.gz -OutFile SDL3.tar.gz
          tar -xvzf SDL3.tar.gz
          cd SDL3-3.2.10

          if (Test-Path build) { Remove-Item build -Recurse -Force }
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="C:/SDL3"
          cmake --build build --config Release

          $dllPath = "build/Release/SDL3.dll"
          if (Test-Path $dllPath) { Remove-Item $dllPath -Force }

          cmake --install build --config Release
        shell: powershell

      - name: Download and install SDL3_image
        run: |
          Invoke-WebRequest -Uri https://github.com/libsdl-org/SDL_image/releases/download/release-3.2.4/SDL3_image-3.2.4.tar.gz -OutFile SDL3_image.tar.gz
          tar -xvzf SDL3_image.tar.gz
          cd SDL3_image-3.2.4

          if (Test-Path build) { Remove-Item build -Recurse -Force }
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="C:/SDL3" -DCMAKE_PREFIX_PATH="C:/SDL3"
          cmake --build build --config Release
          cmake --install build --config Release
        shell: powershell

      - name: Configure project
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="C:/SDL3"

      - name: Build project
        run: cmake --build build --config Release --verbose

      - name: Copy SDL DLLs to build output
        run: |
          Copy-Item -Path "C:/SDL3/bin/SDL3.dll" -Destination "build/Release" -Force
          Copy-Item -Path "C:/SDL3/bin/SDL3_image.dll" -Destination "build/Release" -Force
          Copy-Item -Path "C:/SDL3/bin/zlib1.dll" -Destination "build/Release" -Force
        shell: powershell
