name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake and Ninja (via Chocolatey)
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
        shell: powershell

      - name: Download and install SDL3
        run: |
          Invoke-WebRequest -Uri https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-3.2.10.tar.gz -OutFile SDL3.tar.gz
          tar -xvzf SDL3.tar.gz
          cd SDL3-3.2.10
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="C:/SDL3"
          cmake --build build
          cmake --install build
        shell: powershell

      - name: Download and install SDL3_image
        run: |
          Invoke-WebRequest -Uri https://github.com/libsdl-org/SDL_image/releases/download/release-3.2.4/SDL3_image-3.2.4.tar.gz -OutFile SDL3_image.tar.gz
          tar -xvzf SDL3_image.tar.gz
          cd SDL3_image-3.2.4
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="C:/SDL3"
          cmake --build build
          cmake --install build
        shell: powershell


    # Configure and build the project
    - name: Configure project
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build --verbose