name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install dependencies (without SDL3 from package manager)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    # Manually install SDL3 from GitHub releases
    - name: Install SDL3
      run: |
        wget https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-3.2.10.zip
        tar -xvzf SDL3-3.0.0.tar.gz
        cd SDL3-3.0.0
        ./configure
        make
        sudo make install

    # Configure and build the project
    - name: Configure project
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build --verbose

    - name: Run tests (optional)
      run: make check
