name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
        shell: powershell

      - name: Clean SDL3 folder
        run: Remove-Item -Recurse -Force -ErrorAction Ignore "C:/SDL3"
        shell: powershell

      - name: Download and extract SDL3
        run: |
          Invoke-WebRequest https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-3.2.10.zip -OutFile SDL3.zip
          Expand-Archive SDL3.zip -DestinationPath SDL3_temp
          cd SDL3_temp\SDL3-3.2.10
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="C:/SDL3" -DSDL_INSTALL_TESTS=OFF
          cmake --build build --config Release

          # Delete existing DLL to avoid install error
          $dll = "build/Release/SDL3.dll"
          if (Test-Path $dll) { Remove-Item $dll -Force }

          cmake --install build --config Release
        shell: powershell

      - name: Download and extract SDL3_image
        run: |
          Invoke-WebRequest https://github.com/libsdl-org/SDL_image/releases/download/release-3.2.4/SDL3_image-3.2.4.zip -OutFile SDL3_image.zip
          Expand-Archive SDL3_image.zip -DestinationPath SDL3_image_temp
          cd SDL3_image_temp\SDL3_image-3.2.4
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="C:/SDL3" -DCMAKE_PREFIX_PATH="C:/SDL3"
          cmake --build build --config Release
          cmake --install build --config Release
        shell: powershell

      - name: Configure Tic-Tac-Toe Project
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="C:/SDL3"
        shell: powershell

      - name: Build Tic-Tac-Toe Project
        run: cmake --build build --config Release
        shell: powershell

      - name: Copy required DLLs
        run: |
          $dlls = @("SDL3.dll", "SDL3_image.dll", "zlib1.dll")
          foreach ($dll in $dlls) {
            $source = "C:/SDL3/bin/$dll"
            if (Test-Path $source) {
              Copy-Item $source -Destination "build/Release" -Force
            }
          }
        shell: powershell
